<a href="https://colab.research.google.com/github/CharlyPierce/AlgebraLineal/blob/main/Aprox_VP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from scipy import linalg

In [ ]:
H,Q=linalg.hessenberg(A)
H,Q

(array([25,  7]), array([ 7, 25]))

#Aproximacion de valores propios por la forma
##A=QR->RQ=A1=QR->RQ=A2=QR->RQ=A3=QR...

In [ ]:
r=6
A=np.array([[25,7],[7,25]])
a=[]
a.append(A)

for i in range(r):
  A1=np.linalg.qr(a[i])
  A2=np.dot(A1[1],A1[0])
  a.append(A2)
for i in range(r+1):
  if(i%3==0):
    print(i)
    print('\n')
    print(a[i])
    print('\n')

0


[[25  7]
 [ 7 25]]


3


[[31.57014724 -2.41519466]
 [-2.41519466 18.42985276]]


6


[[31.9859666  0.4430244]
 [ 0.4430244 18.0140334]]




#Aproximacion de valores propios por la forma 
##A-SI=QR->RQ+SI=A1->A1-SI=QR->RQ+SI=A2->A2-SI=QR->RQ+si=A3->A3-SI=QR...

In [ ]:
r=6
asi=[]
a=[]

A=np.array([[25,7],[7,25]])
a.append(A)


for i in range(r):
  s=np.random.randint(10)
  SI=(s*I)*-1
  asi.append(np.add(a[i],SI))
  A1=np.linalg.qr(asi[i])
  A2=np.add(np.dot(A1[1],A1[0]),-SI)
  a.append(A2)
for i in range(r+1):
  if(i%3==0):
    print(i)
    print('\n')
    print(a[i])
    print('\n')


0


[[25  7]
 [ 7 25]]


3


[[31.72851329 -1.93057218]
 [-1.93057218 18.27148671]]


6


[[31.99208226  0.33284487]
 [ 0.33284487 18.00791774]]


